### ISSUE TITLE
[luci-app-openvpn] Push and other config options quickly disappear after Advanced Configuration->VPN is entered

### ISSUE THREAD

**Issue by Menion2k** [openwrt/luci#1291]
Hi. I'm running Luci openvpn-app 17.219.28675-9ee26ac-1 in LEDE
Also with the previous version, if I enter the VPN tab in Advanced Configuration, several usefull push parameters are quickly displayed, then disappear leaving only "Configure cliend mode"
Attached a screenshot I have quickly taken when entering in the VPN tab:

![image](https://user-images.githubusercontent.com/23497448/29116806-57a1ef96-7cfc-11e7-936b-2f3623ad3532.png)

This is the UCI config file content:

```
config openvpn 'myvpn'
        option verb '3'
        option proto 'tcp'
        option dev 'tun'
        option log '/tmp/openvpn.log'
        option ca '/etc/openvpn/ca.crt'
        option cert '/etc/openvpn/my-server.crt'
        option key '/etc/openvpn/my-server.key'
        option dh '/etc/openvpn/dh2048.pem'
        list push 'redirect-gateway def1'
        list push 'dhcp-option DNS 192.168.182.1'
        option port '8294'
        option server '10.12.0.0 255.255.255.0'
        option keepalive '10 120'
        option enabled '1'
        option comp_lzo 'adaptive'

```

**Comment by Wedmer** [comment]
Looks like duplicate #887 
Can you provide screenshot after options disappeared?

**Comment by Menion2k** [comment]
Yes, I confirm it is the duplicate of #887
Here you have the "after" screenshot:

![image](https://user-images.githubusercontent.com/23497448/29214308-23fc4fcc-7ea7-11e7-8e61-2072de62c937.png)

**Comment by Wedmer** [comment]
So you have to get upstream version then.
This problem was fixed with #1123.

**Comment by Menion2k** [comment]
Thanks
I run LEDE, so I guess I have to manually patch or wait for version bump

**Comment by Menion2k** [comment]
Hi
Actually it seems that the lede-17.01 is not updated
Who is in charge of align it with master?

**Comment by adilou1981** [comment]
Hello,

I am using git-18.201.27126-7bf0367-1  and still get the problem ? !

**Comment by gigafunk** [comment]
Powered by LuCI openwrt-18.06 branch (git-18.228.31946-f64b152) / OpenWrt 18.06.1 r7258-5eb055306f 

I deleted the sample configs before I tried to make a new one and now I have no options at all
![capture](https://user-images.githubusercontent.com/1330883/45142348-2a0f5680-b16d-11e8-8c2f-be8027b4131c.JPG)

**Comment by dibdot** [comment]
shoul be fixed in trunk.
