### ISSUE TITLE
luci-theme-bootstrap: Buttons at Status/Overview/Associated Stations hard to use

### ISSUE THREAD

**Issue by wdpi** [openwrt/luci#5693]
## Steps to reproduce:

1. go to: Network → Wireless → Edit (one of your Wireless Networks) → Interface Configuration → MAC Filter
2. set "Allow all except listed"
3. add a MAC (probably not necessary for reproducing) in MAC-List
4. Save
5. Save & Apply

## Actual behavior:

go to: Status/Overview/Associated Stations

The Buttons on the right side of every associated station now are not just Buttons labelled "Disconnect" but a combination of Button and Combo box roughly divided into two halves by a vertical line.
The left part contains the text "Disc" while the right one is empty except a Combo box arrow close to the vertical line.

![image](https://user-images.githubusercontent.com/100048532/155033129-64bfb0a9-404c-4252-930b-faa45beb3b7b.png)

The Combo box contains the items "Disconnect" and "Add to Blacklist".
![image](https://user-images.githubusercontent.com/100048532/155033346-ad906514-310f-4189-b07a-258ee9994a54.png)

Opening the Combo box is quite hard since just a relatively small area around the arrow triggers that behaviour - clicking at the most parts of the button just disconnects immediately instead of opening the Combo box.
![image](https://user-images.githubusercontent.com/100048532/155033725-b66e1144-8229-4528-aa54-6cfb57ca963e.png)

## Expected behavior:

A Button/Combo box layout like e.g. the "Save & Apply" Button would be more clear.
![image](https://user-images.githubusercontent.com/100048532/155033449-912a0395-82f9-4d96-ae14-3e4b626d6f7b.png)

## Additional Information:
luci-theme-bootstrap git-22.047.35373-cc582eb

**Comment by jow-** [comment]
Please attach a screenshot

**Comment by wdpi** [comment]
Done.
I did't know it was possible and so easy.

**Comment by jow-** [comment]
Which version of OpenWrt is that? Did you upgrade individual LuCI components?

**Comment by jow-** [comment]
Was able to reproduce it. Fix pushed.

**Comment by wdpi** [comment]
I have 
openwrt-21.02.1-ath79-generic-tplink_archer-c6-v2-squashfs-factory.bin 
installed.

Powered by LuCI openwrt-21.02 branch (git-21.295.67054-13df80d) / 
OpenWrt 21.02.1 r16325-88151b8303

The problem existed in this version already, so I updated to 
luci-theme-bootstrap git-22.047.35373-cc582eb - which did not solve the 
problem.

Nothing else.
