### ISSUE TITLE
„Weblate“, a lot of errors, missing files, old files conflicting, as they no longer exist. (Migration problem to 24.X)

### ISSUE THREAD

**Issue by dziugas1959** [openwrt/luci#7528]
### Is there an existing issue for this?

- [X] I have searched among all existing issues (including closed issues)

### screenshots or captures

![paveikslas](https://github.com/user-attachments/assets/9901895b-e46e-42fb-9a8e-0aaed1abeb26)
![paveikslas](https://github.com/user-attachments/assets/110a7342-1485-489f-bba4-d99c8e320fca)
![paveikslas](https://github.com/user-attachments/assets/9d956276-5a31-4980-b611-904a5be2e2ad)

### Actual behaviour

Errors are shown, appeared a month ago.

### Expected behaviour

None of these should appear.

### Steps to reproduce

1. go to: https://hosted.weblate.org/projects/openwrt/

### Additional Information

```shell
„Weblate 5.10-dev“
```

### What browsers do you see the problem on?

Firefox

**Comment by systemcrash** [comment]
This is the result of removing the English translations, since they're identical to the GUI.

**Comment by dannil** [comment]
Do we need a maintainer with Weblate access to configure it properly then? I assume it's a consequence of https://github.com/openwrt/luci/commit/0ca52ebe27e96f01b82250e58a375bac0def9561?

**Comment by hnyman** [comment]
It is due to that commit, but it just highlighted the underlying problem that a dozen apps in Weblate have been configured to have en .po file as template, instead of proper templates .pot

It requires manual config for those faulty apps in Weblate config.

**Comment by hnyman** [comment]
But so far 24.10 is already equal to master, so there is no backport need.
(They will likely deviate soon, but right now they are equal)

**Comment by hnyman** [comment]
I fixed the wrong template path

**Comment by dziugas1959** [comment]
> I fixed the wrong template path

Still a phantom file exists, that every language shows an error for:
![paveikslas](https://github.com/user-attachments/assets/c837a779-62e4-47a8-aa7b-8dfc9d757773)
![paveikslas](https://github.com/user-attachments/assets/b556b864-7870-4fd3-a8da-48b3a5d254a9)
Only a maintainer can fix this, this was addressed in this post, though not fixed, even when marked here as „completed“.

**Comment by hnyman** [comment]
Please note that some of the warnings are shown for historical reasons, e.g. in your screenshot "appeared month ago, last seen a month ago".
So some error conditions / displays also clear themselves via time.

But I still re-opened the issue as you wish.

**Comment by dziugas1959** [comment]
From my understanding, this is a bug in „Weblate“, it thinks that there is a file, that no longer exists, as such, shows an error.

**Comment by hnyman** [comment]
> „Weblate“, it thinks that there is a file, that no longer exists, as such, shows an error

It thought so, a month ago. **But not any more.**  Like it says in the screenshots.
To my understanding, it just shows the error message for a while for some reason. Strange, but still.

![image](https://github.com/user-attachments/assets/d73b84b3-b4f8-4941-a2f6-3d4d4a48b7a2)

I do not find any actual errors in the system admin console. 
Only the Glossary component shows the error signs, but when going there, all error notices leads to this same Lithuanian thing...

And naturally we have no real insight into Weblate internals. We are just a downstream user of the service.

**Comment by dziugas1959** [comment]
> > „Weblate“, it thinks that there is a file, that no longer exists, as such, shows an error
> 
> It thought so, a month ago. **But not any more.** Like it says in the screenshots. To my understanding, it just shows the error message for a while for some reason. Strange, but still.
> 
> ![image](https://private-user-images.githubusercontent.com/7926856/401572230-d73b84b3-b4f8-4941-a2f6-3d4d4a48b7a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY2MzYwNDAsIm5iZiI6MTczNjYzNTc0MCwicGF0aCI6Ii83OTI2ODU2LzQwMTU3MjIzMC1kNzNiODRiMy1iNGY4LTQ5NDEtYTJmNi0zZDRkNGE0OGI3YTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTFUMjI0OTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDA0YzYyZGNkOWNkOGMxZjg1ZDQ4NTQ2MDZlMmVjOTlhMDg1NTg2OGU0YzVjMzI2MmM0ZDEyNjE5MWMxODdkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.o7uR4Ma7T-4_UPw3Rgmhql6xAKGr6WxFZyEPU-dvPXU)
> 
> I do not find any actual errors in the system admin console. Only the Glossary component shows the error signs, but when going there, all error notices leads to this same Lithuanian thing...
> 
> And naturally we have no real insight into Weblate internals. We are just a downstream user of the service.

Try doing what the error message says on top of that: „_Please fix this by removing duplicated strings with same identifier from the translation files._“
Most likely, this was a string, that was duplicated with the English (non-developer) and I just copied the glossary translation, which was fine, until English (non-developer) was removed, causing this double phantom string to exist.

Try checking the ID for the place of this string (_IPv6_) and removing it, then re-adding it. My guess, why it doesn't show an error in administration, is most likely because, it doesn't exist and „Weblate“ developers did not account for this type of bug to happen.

**Comment by dziugas1959** [comment]
New problems, this time with the Firmware Wizard, Bulgarian.

![Image](https://github.com/user-attachments/assets/510c0022-4098-43ba-936a-1c27f7c6a285)

**Comment by hnyman** [comment]
Actually, like I predicted, the announcements about old errors got timed out and went away.
The old config related error (that this issue report is about) was fixed by me last week.

Now there is just a "normal" conflict.
I have no access to Firmware wizard repo, so I sent a note to @aparcar. Also @jow- should be able to fix that.

**Comment by systemcrash** [comment]
Actually, I opened a ticket with weblate 😉

They opened this: 

https://github.com/WeblateOrg/weblate/issues/13511

**Comment by dziugas1959** [comment]
Ideally, issues should only be closed when fixed, since the entire component is locked from any edits. Hopefully this will be fixed in a timely manner.

**Comment by hnyman** [comment]
> the entire component is locked from any edits. Hopefully this will be fixed in a timely manner.

Feel free to author a fix PR for the firmware wizard git repo, and then hope that somebody with merge rights there merges it in. You have just as much power in that repo as I do.
